name: 🐛 Bug Report
description: Report a bug in Plant-it.
labels:
  - bug
body:
  - type: checkboxes
    attributes:
      label: Avoid duplicated bug reports
      description: Please avoid bug report duplication
      options:
        - label: I've found a bug and checked that there are no open or closed bug report related to this.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: Please provide a brief description of the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Local environment
      description: If applicable, please provide additional information related to the environment you are using.
      placeholder: |
        1. backend version and app version
        2. content of docker-compose.yml file (remember to hide possible sensitive info)
        3. content of backend.env file (remember to hide possible sensitive info)
        4. app log
        5. output of the docker compose log
